name = "monitor"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "monitor"
database_id = "7ec0d2ba-6f40-4bc0-9ae8-2e539f1aefe3"

[version_metadata]
binding = "CF_VERSION_METADATA"
